/**
 * Intelligence Node Definitions
 * OSINT, GEOINT, Analysis, and Output nodes
 */

import type { NodeDefinition } from '../types';

export const INTELLIGENCE_NODE_DEFINITIONS: NodeDefinition[] = [
  // ==================== OSINT NODES ====================
  {
    type: 'osint-social-media',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Social Media Monitor',
    description: 'Monitor social media platforms for keywords, hashtags, and mentions',
    icon: 'Twitter',
    color: '#1DA1F2',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-domain',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Domain Intelligence',
    description: 'Gather domain information: WHOIS, DNS, subdomains, SSL certificates',
    icon: 'Globe',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-people-search',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'People Search',
    description: 'Search for people by name, email, phone, or username',
    icon: 'Users',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-company',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Company Intelligence',
    description: 'Gather company information: employees, tech stack, news, social presence',
    icon: 'Building2',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-dark-web',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Dark Web Monitor',
    description: 'Monitor dark web sources for keywords and breach data',
    icon: 'Shield',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-news-tracker',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'News & Media Tracker',
    description: 'Track news articles and media mentions with sentiment analysis',
    icon: 'Newspaper',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-code-search',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Code Repository Search',
    description: 'Search GitHub/GitLab for code, credentials, and repositories',
    icon: 'Code',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'osint-image-intel',
    category: 'intelligence',
    subcategory: 'OSINT',
    name: 'Image Intelligence',
    description: 'Reverse image search and EXIF data extraction',
    icon: 'Image',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
  },

  // ==================== GEOINT NODES ====================
  {
    type: 'geoint-geocoding',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'Geocoding',
    description: 'Convert addresses to coordinates and vice versa',
    icon: 'MapPin',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-satellite',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'Satellite Imagery',
    description: 'Retrieve satellite imagery for locations and date ranges',
    icon: 'Satellite',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-flight-tracking',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'Flight Tracking',
    description: 'Track flights in real-time and historical data',
    icon: 'Plane',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-ship-tracking',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'Ship Tracking',
    description: 'Track maritime vessels and port information',
    icon: 'Ship',
    color: '#06b6d4',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-ip-geolocation',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'IP Geolocation',
    description: 'Get geographic location and ISP info from IP addresses',
    icon: 'Network',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-weather',
    category: 'intelligence',
    subcategory: 'GEOINT',
    name: 'Weather Data',
    description: 'Get current and historical weather data for locations',
    icon: 'Cloud',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },

  // ==================== ANALYSIS NODES ====================
  {
    type: 'intel-entity-extraction',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Entity Extraction',
    description: 'Extract entities (emails, phones, IPs, URLs) from text',
    icon: 'Search',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-data-enrichment',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Data Enrichment',
    description: 'Enrich extracted entities with additional data sources',
    icon: 'Database',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-relationship-mapper',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Relationship Mapper',
    description: 'Build entity relationship graphs and identify connections',
    icon: 'GitBranch',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-timeline-builder',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Timeline Builder',
    description: 'Sort events chronologically and merge data streams',
    icon: 'Clock',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-geofencing',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Geofencing',
    description: 'Define boundaries and check if coordinates are within them',
    icon: 'Map',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-pattern-detection',
    category: 'intelligence',
    subcategory: 'Analysis',
    name: 'Pattern Detection',
    description: 'Identify patterns, frequencies, and anomalies in data',
    icon: 'TrendingUp',
    color: '#ec4899',
    inputs: 1,
    outputs: 1,
  },

  // ==================== OUTPUT NODES ====================
  {
    type: 'intel-map-visualization',
    category: 'intelligence',
    subcategory: 'Visualization',
    name: 'Map Visualization',
    description: 'Display data on interactive maps with markers and heatmaps',
    icon: 'Map',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-report-generator',
    category: 'intelligence',
    subcategory: 'Output',
    name: 'Intelligence Report',
    description: 'Generate comprehensive intelligence reports with findings',
    icon: 'FileText',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-data-export',
    category: 'intelligence',
    subcategory: 'Output',
    name: 'Data Export',
    description: 'Export intelligence data to CSV, JSON, Excel, or database',
    icon: 'Download',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
];

