/**
 * Node Definitions
 * Comprehensive integration library similar to n8n
 * Organized by functional subcategories
 */

import type { NodeDefinition, NodeType } from '../types';
import { INTELLIGENCE_NODE_DEFINITIONS } from './intelligenceNodes';

export const NODE_DEFINITIONS: NodeDefinition[] = [
  // ==================== 1. WORKFLOW TRIGGERS ====================
  {
    type: 'purchased-data-input',
    category: 'trigger',
    subcategory: 'Workflow Triggers',
    name: 'Spectr Live Data',
    description: 'Access real-time intelligence data from SPECTR SYSTEMS data marketplace based on your subscriptions',
    icon: 'ShoppingBag',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'connected-data-input',
    category: 'trigger',
    subcategory: 'Workflow Triggers',
    name: 'Connected Data Input',
    description: 'Inputs data from external systems that you have connected to your workflow',
    icon: 'Link',
    color: '#3b82f6',
    inputs: 0,
    outputs: 1,
  },
  // ==================== 2. INTELLIGENCE NODES ====================
  {
    type: 'osint-enrichment',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'OSINT Enrichment',
    description: 'Collects open-source information about entity (company, individual, website)',
    icon: 'FileSearch',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'corporate-registry',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Corporate Registry',
    description: 'Queries official databases for corporate info and status',
    icon: 'Building2',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'sanctions-blacklist',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Sanctions & Blacklist',
    description: 'Checks entity against sanctions, watchlists, or blacklists',
    icon: 'Shield',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'social-footprint',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Social Footprint',
    description: 'Gathers public social media / web presence for risk signals',
    icon: 'Users',
    color: '#06b6d4',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'domain-verification',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Domain / Website Verification',
    description: 'Confirms website authenticity, domain age, infrastructure',
    icon: 'Globe',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'risk-scoring',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Risk Scoring',
    description: 'Aggregates intelligence into a numeric/categorical risk score',
    icon: 'Gauge',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'gdpr-compliance',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'GDPR Compliance',
    description: 'Validates that personal data usage complies with GDPR / regional privacy rules',
    icon: 'Lock',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'historical-correlation',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Historical Correlation',
    description: 'Matches entity with historical incidents or alerts for pattern detection',
    icon: 'Clock',
    color: '#64748b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-entity-extraction',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Entity Extraction',
    description: 'Extracts and resolves entities from unstructured text, handles aliases and subsidiaries',
    icon: 'Search',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-data-enrichment',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Data Enrichment',
    description: 'Enriches entity data with additional intelligence from multiple sources',
    icon: 'Database',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-relationship-mapper',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Relationship Mapper',
    description: 'Maps relationships between entities, identifies dependencies and connections',
    icon: 'Network',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'intel-data-export',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Data Export',
    description: 'Exports intelligence data to external systems via API or webhook',
    icon: 'Download',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-geocoding',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Geocoding',
    description: 'Converts addresses and locations to geographic coordinates',
    icon: 'MapPin',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-ship-tracking',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Ship Tracking',
    description: 'Tracks shipping routes and identifies critical logistics chokepoints',
    icon: 'Ship',
    color: '#06b6d4',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'geoint-enrichment',
    category: 'intelligence',
    subcategory: 'Intelligence Nodes',
    name: 'Geographic Enrichment',
    description: 'Enriches data with geographic intelligence including weather, routes, and regional risks',
    icon: 'Map',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  // ==================== 3. DECISION NODES ====================
  {
    type: 'risk-level-decision',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Risk Level Decision',
    description: 'Determines low / medium / high risk based on intelligence output',
    icon: 'GitBranch',
    color: '#f59e0b',
    inputs: 1,
    outputs: 3,
  },
  {
    type: 'approval-gate',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Approval Gate',
    description: 'Determines if human approval is required before proceeding',
    icon: 'CheckSquare',
    color: '#10b981',
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'escalation',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Escalation',
    description: 'Routes high-risk cases to senior staff or compliance teams',
    icon: 'ArrowUpDown',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'branching',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Branching',
    description: 'Directs workflow paths based on risk score, GDPR validation, or other conditions',
    icon: 'Route',
    color: '#6366f1',
    inputs: 1,
    outputs: 3,
  },
  {
    type: 'condition',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Condition',
    description: 'Evaluates conditions and routes workflow based on true/false outcomes',
    icon: 'GitBranch',
    color: '#f59e0b',
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'decision-action',
    category: 'action',
    subcategory: 'Decision Nodes',
    name: 'Decision Action',
    description: 'Makes automated decisions based on risk thresholds and policy rules',
    icon: 'CheckSquare',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  // ==================== 4. ACTION NODES ====================
  {
    type: 'notify-team',
    category: 'action',
    subcategory: 'Action Nodes',
    name: 'Notify Team',
    description: 'Sends alerts/notifications to Slack, email, or internal dashboards',
    icon: 'Bell',
    color: '#3b82f6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'request-documents',
    category: 'action',
    subcategory: 'Action Nodes',
    name: 'Request Documents',
    description: 'Automatically requests supporting documents if flagged',
    icon: 'FileText',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'account-restriction',
    category: 'action',
    subcategory: 'Action Nodes',
    name: 'Account Restriction',
    description: 'Applies temporary blocks or restrictions on account/vendor until review',
    icon: 'Lock',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'ticket-generation',
    category: 'action',
    subcategory: 'Action Nodes',
    name: 'Ticket Generation',
    description: 'Creates tasks/tickets for manual investigation or verification',
    icon: 'ClipboardList',
    color: '#06b6d4',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'log-outcome',
    category: 'action',
    subcategory: 'Action Nodes',
    name: 'Log Outcome',
    description: 'Writes execution results to audit logs for compliance and replay',
    icon: 'FileCheck',
    color: '#64748b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'database',
    category: 'action',
    subcategory: 'Data Storage',
    name: 'Database',
    description: 'Stores and retrieves data from databases, tracks historical data and trends',
    icon: 'Database',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'ai-agent',
    category: 'action',
    subcategory: 'AI & Code',
    name: 'AI Agent',
    description: 'Uses AI to process, analyze, and synthesize data with custom prompts',
    icon: 'Brain',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'code',
    category: 'action',
    subcategory: 'AI & Code',
    name: 'Code',
    description: 'Execute custom JavaScript code for data transformation and logic',
    icon: 'Code',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'web-scraper',
    category: 'trigger',
    subcategory: 'Workflow Triggers',
    name: 'Webscraper',
    description: 'Advanced web scraping with AI-powered field detection, dynamic content handling, anti-bot measures, and intelligent data normalization',
    icon: 'FileSearch',
    color: '#06b6d4',
    inputs: 0,
    outputs: 1,
  },
  // ==================== 5. UTILITY / GOVERNANCE NODES ====================
  {
    type: 'audit-logging',
    category: 'action',
    subcategory: 'Utility / Governance Nodes',
    name: 'Audit Logging',
    description: 'Captures inputs, outputs, decisions, intelligence sources for every step',
    icon: 'FileCheck',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'execution-control',
    category: 'action',
    subcategory: 'Utility / Governance Nodes',
    name: 'Execution Control',
    description: 'Supports pause, resume, retry, or abort of workflow runs',
    icon: 'Play',
    color: '#10b981',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'human-override',
    category: 'action',
    subcategory: 'Utility / Governance Nodes',
    name: 'Human Override',
    description: 'Ensures human can intervene before irreversible actions are executed',
    icon: 'UserCheck',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'rate-quota',
    category: 'action',
    subcategory: 'Utility / Governance Nodes',
    name: 'Rate / Quota',
    description: 'Controls usage of live data subscriptions to prevent overuse or billing issues',
    icon: 'Gauge',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 1,
  },
  // ==================== 6. APP NODES ====================
  {
    type: 'form',
    category: 'action',
    subcategory: 'App Nodes',
    name: 'Form',
    description: 'Collect structured data from users (customers, vendors, partners) and feed it into workflows',
    icon: 'FormInput',
    color: '#3b82f6',
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'login-authentication',
    category: 'action',
    subcategory: 'App Nodes',
    name: 'Login and Authentication',
    description: 'Secure authentication & user management for businesses and their end-users',
    icon: 'Lock',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'redirection',
    category: 'action',
    subcategory: 'App Nodes',
    name: 'Redirection',
    description: 'Acts as a "bridge" between company website and your nodes (Forms, Login), handling smooth redirection and session tracking',
    icon: 'ArrowUpDown',
    color: '#06b6d4',
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'dashboard',
    category: 'output',
    subcategory: 'App Nodes',
    name: 'Dashboard',
    description: 'Let company admins see submissions, workflow progress, AI scoring, risk levels, and logs',
    icon: 'LayoutDashboard',
    color: '#8b5cf6',
    inputs: 1,
    outputs: 0,
  },
  {
    type: 'website',
    category: 'action',
    subcategory: 'App Nodes',
    name: 'Website',
    description: 'Create and manage website pages, content, and user interactions',
    icon: 'Globe',
    color: '#f59e0b',
    inputs: 1,
    outputs: 1,
  },
  // ==================== 7. INTEGRATION NODES ====================
  {
    type: 'integration',
    category: 'action',
    subcategory: 'Integration Nodes',
    name: 'Integration',
    description: 'Users can integrate any app into this system',
    icon: 'Link',
    color: '#6366f1',
    inputs: 1,
    outputs: 1,
  },
];

// Functional subcategories for organization
export const SUBCATEGORIES: Record<string, { name: string; icon: string }> = {
  'Workflow Triggers': { name: 'Workflow Triggers', icon: 'Play' },
  'Intelligence Nodes': { name: 'Intelligence Nodes', icon: 'Brain' },
  'Decision Nodes': { name: 'Decision Nodes', icon: 'GitBranch' },
  'Action Nodes': { name: 'Action Nodes', icon: 'Zap' },
  'Utility / Governance Nodes': { name: 'Utility / Governance Nodes', icon: 'Shield' },
  'App Nodes': { name: 'App Nodes', icon: 'Smartphone' },
  'Integration Nodes': { name: 'Integration Nodes', icon: 'Link' },
  'Control Flow': { name: 'Control Flow & Logic', icon: 'GitBranch' },
  'Data Transformation': { name: 'Data Transformation', icon: 'Shuffle' },
  'Data Sources': { name: 'Data Sources', icon: 'Globe' },
  'AI & Code': { name: 'AI & Code', icon: 'Code' },
  'Intelligence': { name: 'Intelligence (OSINT/GEOINT)', icon: 'Brain' },
  'Data Storage': { name: 'Data Storage', icon: 'Database' },
  'Communication': { name: 'Communication', icon: 'MessageSquare' },
  'Business Operations': { name: 'Business Operations', icon: 'Briefcase' },
  'Productivity & Development': { name: 'Productivity & Development', icon: 'Code' },
  'Marketing & Engagement': { name: 'Marketing & Engagement', icon: 'Megaphone' },
  'Infrastructure': { name: 'Infrastructure', icon: 'Cloud' },
  'Documents': { name: 'Documents', icon: 'FileText' },
  'Outputs': { name: 'Outputs', icon: 'Send' },
};

// Group nodes by category
export const NODE_CATEGORIES = {
  trigger: {
    name: 'Triggers',
    description: 'Start your workflow',
    nodes: NODE_DEFINITIONS.filter(n => n.category === 'trigger'),
  },
  action: {
    name: 'Actions',
    description: 'Process and transform data',
    nodes: NODE_DEFINITIONS.filter(n => n.category === 'action'),
  },
  output: {
    name: 'Outputs',
    description: 'Send or store results',
    nodes: NODE_DEFINITIONS.filter(n => n.category === 'output'),
  },
  intelligence: {
    name: 'Intelligence',
    description: 'OSINT, GEOINT, and analysis tools',
    nodes: NODE_DEFINITIONS.filter(n => n.category === 'intelligence'),
  },
};

// Group nodes by subcategory
export function getNodesBySubcategory(): Record<string, NodeDefinition[]> {
  const grouped: Record<string, NodeDefinition[]> = {};
  
  NODE_DEFINITIONS.forEach(node => {
    const subcat = node.subcategory || 'Other';
    if (!grouped[subcat]) {
      grouped[subcat] = [];
    }
    grouped[subcat].push(node);
  });
  
  return grouped;
}

// Get node definition by type
export function getNodeDefinition(type: NodeType): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find(n => n.type === type);
}

// Get node color by type
export function getNodeColor(type: NodeType): string {
  return getNodeDefinition(type)?.color || '#64748b';
}

// Search nodes
export function searchNodes(query: string): NodeDefinition[] {
  const q = query.toLowerCase();
  return NODE_DEFINITIONS.filter(
    n => n.name.toLowerCase().includes(q) || 
         n.description.toLowerCase().includes(q) ||
         (n.subcategory && n.subcategory.toLowerCase().includes(q))
  );
}
